"""Add a setting for pinning initial messages

Revision ID: 60cf45e1ea54
Revises: 735750092b40
Create Date: 2025-12-16 13:59:58.272381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cf45e1ea54'
down_revision = '735750092b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('sticky_first_message', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'sticky_first_message')
    # ### end Alembic commands ###
