"""Adding hunt data to database

Revision ID: 63a1fe96802f
Revises: 8e56c70e52e4
Create Date: 2023-12-12 20:04:51.923759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a1fe96802f'
down_revision = '8e56c70e52e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hunt_settings',
    sa.Column('guild_id', sa.BIGINT(), nullable=False),
    sa.Column('guild_name', sa.Text(), nullable=True),
    sa.Column('hunt_url', sa.Text(), nullable=True),
    sa.Column('hunt_url_sep', sa.Text(), nullable=True),
    sa.Column('hunt_round_url', sa.Text(), nullable=True),
    sa.Column('discord_bot_channel', sa.Text(), nullable=True),
    sa.Column('discord_bot_emoji', sa.Text(), nullable=True),
    sa.Column('discord_use_voice_channels', sa.BIGINT(), nullable=True),
    sa.Column('drive_parent_id', sa.Text(), nullable=True),
    sa.Column('drive_nexus_sheet_id', sa.Text(), nullable=True),
    sa.Column('drive_resources_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_hunt_settings'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hunt_settings')
    # ### end Alembic commands ###
