"""add hunt round unique constraints

Revision ID: 735750092b40
Revises: ee98b77c7cec
Create Date: 2024-01-09 08:22:28.198129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735750092b40'
down_revision = 'ee98b77c7cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hunt_settings', sa.Column('drive_resources_id', sa.Text(), nullable=True))
    op.add_column('hunt_settings', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('hunt_settings', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.execute("DELETE FROM puzzle_notes WHERE puzzle_id IS NULL;")
    op.alter_column('puzzle_notes', 'puzzle_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint('uq_hunt_settings_guild_id_hunt_name', 'hunt_settings', ['guild_id', 'hunt_name'])
    op.create_unique_constraint('uq_round_data_hunt_id_name', 'round_data', ['hunt_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_round_data_hunt_id_name', 'round_data', type_='unique')
    op.drop_constraint('uq_hunt_settings_guild_id_hunt_name', 'hunt_settings', type_='unique')
    op.alter_column('puzzle_notes', 'puzzle_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('hunt_settings', 'end_time')
    op.drop_column('hunt_settings', 'start_time')
    op.drop_column('hunt_settings', 'drive_resources_id')
    # ### end Alembic commands ###
