"""Add separate timestamp for requesting deletion of a puzzle

Revision ID: b8b8a390aa12
Revises: 33c7d5d10a35
Create Date: 2023-12-16 22:24:28.595269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b8b8a390aa12"
down_revision = "33c7d5d10a35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "puzzle_data", sa.Column("delete_request", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("puzzle_data", "delete_request")
    # ### end Alembic commands ###
