"""Move hunt settings to a new table

It's unfortuante, but this allows us to make a more rational primary key

Revision ID: d9415db923e5
Revises: f17dd3158459
Create Date: 2023-12-19 14:27:05.718189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9415db923e5'
down_revision = 'f17dd3158459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hunt_settings')
    op.create_table('hunt_settings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BIGINT(), nullable=True),
    sa.Column('hunt_name', sa.Text(), nullable=True),
    sa.Column('hunt_url', sa.Text(), nullable=True),
    sa.Column('hunt_url_sep', sa.Text(), nullable=True),
    sa.Column('hunt_round_url', sa.Text(), nullable=True),
    sa.Column('drive_hunt_folder_id', sa.Text(), nullable=True),
    sa.Column('drive_nexus_sheet_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_per_hunt_settings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hunt_settings')
    op.create_table('hunt_settings',
    sa.Column('guild_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('hunt_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hunt_url_sep', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hunt_round_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('drive_nexus_sheet_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('guild_id', name='pk_hunt_settings')
    )
    # ### end Alembic commands ###
