"""add table for rounds

Revision ID: ea4259733a37
Revises: d9415db923e5
Create Date: 2023-12-20 20:44:10.591920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ea4259733a37"
down_revision = "d9415db923e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "round_data",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("category_id", sa.BIGINT(), nullable=True),
        sa.Column("solved_category_id", sa.BIGINT(), nullable=True),
        sa.Column("hunt_id", sa.BIGINT(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_round_data")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("round_data")
    # ### end Alembic commands ###
