"""add foreign keys and notes table

Revision ID: ee98b77c7cec
Revises: 8c5542d2cd84
Create Date: 2024-01-07 10:57:30.515176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee98b77c7cec"
down_revision = "8c5542d2cd84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_round_data_category_id"), "round_data", ["category_id"])
    op.create_foreign_key(
        op.f("fk_puzzle_data_round_id_round_data"),
        "puzzle_data",
        "round_data",
        ["round_id"],
        ["category_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_round_data_hunt_id_hunt_settings"),
        "round_data",
        "hunt_settings",
        ["hunt_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_hunt_settings_guild_id_guilds"),
        "hunt_settings",
        "guilds",
        ["guild_id"],
        ["id"],
        onupdate="CASCADE",
    )

    op.add_column("round_data", sa.Column("round_url", sa.Text(), nullable=True))
    op.add_column("round_data", sa.Column("round_url_sep", sa.Text(), nullable=True))

    op.create_table(
        "puzzle_notes",
        sa.Column("note_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("puzzle_id", sa.BIGINT(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("user", sa.Text(), nullable=True),
        sa.Column("jump_url", sa.Text(), nullable=True),
        sa.Column("added_time", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["puzzle_id"],
            ["puzzle_data.id"],
            name=op.f("fk_puzzle_notes_puzzle_id_puzzle_data"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("note_id", name=op.f("pk_puzzle_notes")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_round_data_hunt_id_hunt_settings"), "round_data", type_="foreignkey"
    )
    op.drop_column("round_data", "round_url_sep")
    op.drop_column("round_data", "round_url")
    op.drop_constraint(
        op.f("fk_puzzle_data_round_id_round_data"), "puzzle_data", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_hunt_settings_guild_id_guilds"), "hunt_settings", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_round_data_category_id"), "round_data", type_="unique")
    op.drop_table("puzzle_notes")
    # ### end Alembic commands ###
