"""add table for puzzle_data

Revision ID: ff7c50e73243
Revises: 63a1fe96802f
Create Date: 2023-12-13 22:03:20.421124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff7c50e73243"
down_revision = "63a1fe96802f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "puzzle_data",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("round_name", sa.Text(), nullable=True),
        sa.Column("round_id", sa.BIGINT(), nullable=True),
        sa.Column("solved_round_id", sa.BIGINT(), nullable=True),
        sa.Column("guild_id", sa.BIGINT(), nullable=True),
        sa.Column("guild_name", sa.Text(), nullable=True),
        sa.Column("channel_id", sa.BIGINT(), nullable=True),
        sa.Column("channel_mention", sa.Text(), nullable=True),
        sa.Column("voice_channel_id", sa.BIGINT(), nullable=True),
        sa.Column("archive_channel_mention", sa.Text(), nullable=True),
        sa.Column("hunt_url", sa.Text(), nullable=True),
        sa.Column("google_sheet_id", sa.Text(), nullable=True),
        sa.Column("google_folder_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("solution", sa.Text(), nullable=True),
        sa.Column("priority", sa.Text(), nullable=True),
        sa.Column("puzzle_type", sa.Text(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("solve_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archive_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delete_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_puzzle_data")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("puzzle_data")
    # ### end Alembic commands ###
